### ISSUE TITLE
Tests vacios

### ISSUE THREAD

**Issue by delucas** [X-Force3/Zork#2]
https://github.com/X-Force3/Zork/blob/449a86471b9724ba5696fef8a83a2c1fccca1828/test/entidades/AventuraTest.java#L6-L20

No es buena práctica commitear pruebas vacías. Se mantienen en un branch hasta que se terminen, se terminan, o se eliminan. `master` tiene que estar entregable siempre

**Comment by jialonso1993** [comment]
Lo vamos a tener en cuenta para la próxima entrega... Gracias!

**Comment by delucas** [comment]
Queda pendiente arreglar los tests.
