### ISSUE TITLE
No devolver nulos

### ISSUE THREAD

**Issue by delucas** [X-Force3/Zork#3]
https://github.com/X-Force3/Zork/blob/449a86471b9724ba5696fef8a83a2c1fccca1828/test/entidades/ConexionTest.java#L48

Traten de no devolver `null`, y si fuera necesario devolver valores nulos, utilizar el patrón Null Object.
La lógica no debería depender de la evaluación de `null`.

**Comment by jialonso1993** [comment]
Corregido. Eliminamos el test porque modificamos la implementación de la clase Conexión. Lo vamos a tener en cuenta...

**Comment by delucas** [comment]
Lo cierro porque se eliminó el test.
