### ISSUE TITLE
Uso de Aserciones

### ISSUE THREAD

**Issue by delucas** [X-Force3/Zork#6]
https://github.com/X-Force3/Zork/blob/449a86471b9724ba5696fef8a83a2c1fccca1828/test/entidades/ProtagonistaTest.java#L83

Tenemos disponible los `assertEquals`, pero también `assertTrue`, `assertFalse`, `assertNull`, etc.
Pueden emplearlos para agregar expresividad a sus pruebas

**Comment by jialonso1993** [comment]
Corregido. Modificamos la manera de realizar las pruebas.

**Comment by delucas** [comment]
:+1:
