### ISSUE TITLE
Aventura hardcodeada

### ISSUE THREAD

**Issue by delucas** [X-Force3/Zork#7]
https://github.com/X-Force3/Zork/blob/449a86471b9724ba5696fef8a83a2c1fccca1828/src/entidades/Protagonista.java#L12-L46

No debería estar hardcodeado en el constructor del personaje ningún dato relativo a ninguna aventura en particular.

**Comment by jialonso1993** [comment]
Corregido. El constructor de Protagonista sólo recibe dos parámetros: String nombreJugador y Ubicacion ubicacionInicial.

**Comment by delucas** [comment]
:+1:
