### ISSUE TITLE
Equals muy complejo

### ISSUE THREAD

**Issue by delucas** [X-Force3/Zork#8]
A veces es tentador utilizar todos los atributos para definir la igualdad, pero con menos suele alcanzar. Recuerden que cada comparación demanda tiempo computacional, y si bien es despreciable, nos perdemos al pensar "¿qué atributos necesito para la igualdad?"

https://github.com/X-Force3/Zork/blob/449a86471b9724ba5696fef8a83a2c1fccca1828/src/entidades/Ubicacion.java#L86-L124

**Comment by jialonso1993** [comment]
Corregido. No se utilizan más los métodos "equals" para saber en qué Ubicacion está el Protagonista. Se compara el atributo nombre de la clase Ubicacion o de la clase Conexion.

**Comment by delucas** [comment]
Mmmm pero no es lo que dije @jialonso1993 ... la cosa es utilizar los atributos necesarios en el equals. Ejemplo: si dos ubicaciones no pueden llamarse igual, con el nombre en el equals ya alcanza para saber que son lo mismo.
En el código **nunca** comparen por un atributo de un objeto, es correcto usar equals allí.

**Comment by jialonso1993** [comment]
Aaah. Está bien. Deberíamos crear un "equals" que sólo compare el nombre de la Ubicacion o de la Conexion entonces (porque no vamos a crear dos objetos de la clase que se llamen de igual manera)... Gracias profe!

**Comment by delucas** [comment]
:+1:
